//! Read-side catalog parity against files written by h5py / libhdf5.
//!
//! Every case here is a silent-data-loss regression: a file libhdf5 reads
//! fine whose contents rust-hdf5 dropped from its listing instead of
//! reporting. Fixtures are generated by h5py at test time; the interpreter
//! comes from `RUST_HDF5_TEST_PYTHON`, else `RUST_HDF5_ORACLE_PYTHON`, else
//! the oracle's pinned env. The tests skip (pass) when none is present, so a
//! machine without h5py stays green.

use rust_hdf5::H5File;

const PINNED_PYTHON: &str = "/home/stevek/micromamba/envs/tomo/bin/python";

fn python() -> Option<&'static str> {
    static PY: std::sync::OnceLock<Option<String>> = std::sync::OnceLock::new();
    PY.get_or_init(|| {
        let candidate = std::env::var("RUST_HDF5_TEST_PYTHON")
            .or_else(|_| std::env::var("RUST_HDF5_ORACLE_PYTHON"))
            .unwrap_or_else(|_| PINNED_PYTHON.to_string());
        if std::path::Path::new(&candidate).exists() {
            Some(candidate)
        } else {
            eprintln!("skipping h5py fixture test: {candidate} not present");
            None
        }
    })
    .as_deref()
}

fn tmp(name: &str) -> std::path::PathBuf {
    use std::sync::atomic::{AtomicU64, Ordering};
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    std::env::temp_dir().join(format!(
        "rust_hdf5_catalog_{}_{}_{}.h5",
        name,
        std::process::id(),
        n
    ))
}

/// Run `body` (top-level python statements) with `path` available as `PATH`.
/// A non-zero exit fails the test; python's traceback reaches the test stderr.
fn h5py_write(py: &str, path: &std::path::Path, body: &str) {
    let script = format!(
        "import h5py, numpy as np\nPATH = r'{}'\n{}\n",
        path.display(),
        body
    );
    let status = std::process::Command::new(py)
        .arg("-c")
        .arg(&script)
        .status()
        .expect("failed to spawn python");
    assert!(
        status.success(),
        "h5py fixture generation failed for {}",
        path.display()
    );
}

/// A contiguous dataset written under `libver=("v110","v110")` carries a
/// *version 4* data-layout message whose body is byte-identical to the
/// version-3 one. Rejecting the version dropped the dataset from the catalog
/// while a chunked dataset in the same file listed fine — the bisected pair
/// this test pins from both sides.
#[test]
fn contiguous_and_chunked_v110_both_list_and_read() {
    let Some(py) = python() else { return };
    let path = tmp("layout_v110");
    h5py_write(
        py,
        &path,
        "with h5py.File(PATH, 'w', libver=('v110', 'v110')) as f:\n\
         \x20   f.create_dataset('contig', data=np.arange(16, dtype='<i4'))\n\
         \x20   ds = f.create_dataset('chunky', (16,), chunks=(16,), dtype='<i4')\n\
         \x20   ds[...] = np.arange(16, dtype='<i4')\n\
         \x20   f.create_group('g')\n",
    );

    let file = H5File::open(&path).unwrap();
    let mut names = file.root_group().dataset_names().unwrap();
    names.sort();
    assert_eq!(names, vec!["chunky".to_string(), "contig".to_string()]);

    let expected: Vec<i32> = (0..16).collect();
    for name in ["contig", "chunky"] {
        let ds = file.dataset(name).unwrap();
        assert_eq!(ds.shape(), &[16], "{name}");
        assert_eq!(ds.read_raw::<i32>().unwrap(), expected, "{name}");
    }

    std::fs::remove_file(&path).ok();
}

/// The same dataset at every `libver` bound h5py offers. `latest` and
/// `v110` are the two that emit a version-4 contiguous layout; `earliest`
/// and `v108` emit version 3. All four must list the dataset and the group.
#[test]
fn contiguous_lists_at_every_libver_bound() {
    let Some(py) = python() else { return };
    for bound in ["earliest", "v108", "v110", "latest"] {
        let path = tmp(&format!("libver_{bound}"));
        let bounds = if bound == "latest" || bound == "earliest" {
            format!("'{bound}'")
        } else {
            format!("('{bound}', '{bound}')")
        };
        h5py_write(
            py,
            &path,
            &format!(
                "with h5py.File(PATH, 'w', libver={bounds}) as f:\n\
                 \x20   f.create_dataset('data', data=np.arange(16, dtype='<i4'))\n\
                 \x20   f.create_group('g')\n"
            ),
        );

        let file = H5File::open(&path).unwrap();
        let root = file.root_group();
        assert_eq!(
            root.dataset_names().unwrap(),
            vec!["data".to_string()],
            "libver {bound}"
        );
        assert_eq!(
            root.group_names().unwrap(),
            vec!["g".to_string()],
            "libver {bound}"
        );
        let data = file.dataset("data").unwrap().read_raw::<i32>().unwrap();
        assert_eq!(data, (0..16).collect::<Vec<i32>>(), "libver {bound}");

        std::fs::remove_file(&path).ok();
    }
}
