//! Read-side catalog parity against files written by h5py / libhdf5.
//!
//! Every case here is a silent-data-loss regression: a file libhdf5 reads
//! fine whose contents rust-hdf5 dropped from its listing instead of
//! reporting. Fixtures are generated by h5py at test time; the interpreter
//! comes from `RUST_HDF5_TEST_PYTHON`, else `RUST_HDF5_ORACLE_PYTHON`, else
//! the oracle's pinned env. The tests skip (pass) when none is present, so a
//! machine without h5py stays green.

use rust_hdf5::{H5File, Hdf5Error, LinkClass};

const PINNED_PYTHON: &str = "/home/stevek/micromamba/envs/tomo/bin/python";

fn python() -> Option<&'static str> {
    static PY: std::sync::OnceLock<Option<String>> = std::sync::OnceLock::new();
    PY.get_or_init(|| {
        let candidate = std::env::var("RUST_HDF5_TEST_PYTHON")
            .or_else(|_| std::env::var("RUST_HDF5_ORACLE_PYTHON"))
            .unwrap_or_else(|_| PINNED_PYTHON.to_string());
        if std::path::Path::new(&candidate).exists() {
            Some(candidate)
        } else {
            eprintln!("skipping h5py fixture test: {candidate} not present");
            None
        }
    })
    .as_deref()
}

fn tmp(name: &str) -> std::path::PathBuf {
    use std::sync::atomic::{AtomicU64, Ordering};
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    std::env::temp_dir().join(format!(
        "rust_hdf5_catalog_{}_{}_{}.h5",
        name,
        std::process::id(),
        n
    ))
}

/// A fresh directory, for the cases whose subject *is* where a file sits:
/// external links resolve their target relative to the directory holding the
/// file that names them, so those fixtures cannot share one.
fn tmp_dir(name: &str) -> std::path::PathBuf {
    use std::sync::atomic::{AtomicU64, Ordering};
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    let dir = std::env::temp_dir().join(format!(
        "rust_hdf5_catalog_{}_{}_{}",
        name,
        std::process::id(),
        n
    ));
    std::fs::create_dir_all(&dir).expect("failed to create fixture directory");
    dir
}

/// Run `body` (top-level python statements) with `path` available as `PATH`,
/// to write a fixture or to assert over one. A non-zero exit — including a
/// failed `assert` — fails the test; python's traceback reaches test stderr.
fn h5py_write(py: &str, path: &std::path::Path, body: &str) {
    let script = format!(
        "import h5py, numpy as np\nPATH = r'{}'\n{}\n",
        path.display(),
        body
    );
    let status = std::process::Command::new(py)
        .arg("-c")
        .arg(&script)
        .status()
        .expect("failed to spawn python");
    assert!(
        status.success(),
        "h5py fixture generation failed for {}",
        path.display()
    );
}

/// A soft link, in both group storage layouts h5py can write it into: the
/// `earliest` bound puts it in a symbol-table entry with cache type 2 and a
/// local-heap value, `latest` puts it in a link message. Either way libhdf5
/// lists the name and `H5Dopen` follows it, so both must here too.
#[test]
fn soft_link_is_listed_and_followed_in_both_group_layouts() {
    let Some(py) = python() else { return };
    for bound in ["earliest", "latest"] {
        let path = tmp(&format!("softlink_{bound}"));
        h5py_write(
            py,
            &path,
            &format!(
                "with h5py.File(PATH, 'w', libver='{bound}') as f:\n\
                 \x20   f.create_dataset('data', data=np.arange(8, dtype='<i4'))\n\
                 \x20   f['soft'] = h5py.SoftLink('/data')\n"
            ),
        );

        let file = H5File::open(&path).unwrap();
        let root = file.root_group();
        assert_eq!(
            root.link_names().unwrap(),
            vec!["data".to_string(), "soft".to_string()],
            "libver {bound}"
        );
        assert!(
            matches!(root.link_class("soft").unwrap(), LinkClass::Soft { path } if path == "/data"),
            "libver {bound}: {:?}",
            root.link_class("soft").unwrap()
        );
        assert!(matches!(root.link_class("data").unwrap(), LinkClass::Hard));

        let expected: Vec<i32> = (0..8).collect();
        assert_eq!(
            file.dataset("soft").unwrap().read_raw::<i32>().unwrap(),
            expected,
            "libver {bound}"
        );

        std::fs::remove_file(&path).ok();
    }
}

/// A soft link whose value is relative to the group holding it, and a soft
/// link that names a group so the traversal has to rewrite a path *prefix*.
#[test]
fn soft_link_resolves_relative_values_and_group_prefixes() {
    let Some(py) = python() else { return };
    let path = tmp("softlink_shapes");
    h5py_write(
        py,
        &path,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   g = f.create_group('g')\n\
         \x20   g.create_dataset('d', data=np.arange(4, dtype='<i4'))\n\
         \x20   g['rel'] = h5py.SoftLink('d')\n\
         \x20   f['galias'] = h5py.SoftLink('/g')\n",
    );

    let file = H5File::open(&path).unwrap();
    let expected: Vec<i32> = (0..4).collect();
    // relative value: '/g/rel' -> '/g/d'
    assert_eq!(
        file.dataset("g/rel").unwrap().read_raw::<i32>().unwrap(),
        expected
    );
    // prefix rewrite: '/galias/d' -> '/g/d'
    assert_eq!(
        file.dataset("galias/d").unwrap().read_raw::<i32>().unwrap(),
        expected
    );

    std::fs::remove_file(&path).ok();
}

/// A dangling soft link is *present* — libhdf5 lists it and fails the open.
/// Reporting it as absent is the loss this pins: the name must be listed and
/// the open must name the link and its unreachable target.
#[test]
fn dangling_soft_link_is_listed_and_reported_as_dangling() {
    let Some(py) = python() else { return };
    let path = tmp("softlink_dangling");
    h5py_write(
        py,
        &path,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f.create_dataset('data', data=np.arange(4, dtype='<i4'))\n\
         \x20   f['gone'] = h5py.SoftLink('/nowhere')\n",
    );

    let file = H5File::open(&path).unwrap();
    let root = file.root_group();
    assert_eq!(
        root.link_names().unwrap(),
        vec!["data".to_string(), "gone".to_string()]
    );
    assert!(
        matches!(root.link_class("gone").unwrap(), LinkClass::Soft { path } if path == "/nowhere")
    );
    match file.dataset("gone").err() {
        Some(Hdf5Error::DanglingLink { link, target }) => {
            assert_eq!(link, "gone");
            assert_eq!(target, "/nowhere");
        }
        other => panic!("expected a dangling-link error, got {other:?}"),
    }

    std::fs::remove_file(&path).ok();
}

/// An external link is listed, its target file and path are readable through
/// `link_class`, and opening through it reads the dataset in the other file.
#[test]
fn external_link_is_listed_with_its_target() {
    let Some(py) = python() else { return };
    let target = tmp("extlink_target");
    let path = tmp("extlink");
    h5py_write(
        py,
        &target,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f.create_dataset('data', data=np.arange(4, dtype='<i4'))\n",
    );
    h5py_write(
        py,
        &path,
        &format!(
            "with h5py.File(PATH, 'w') as f:\n\
             \x20   f.create_dataset('local', data=np.arange(4, dtype='<i4'))\n\
             \x20   f['ext'] = h5py.ExternalLink(r'{}', '/data')\n",
            target.display()
        ),
    );

    let file = H5File::open(&path).unwrap();
    let root = file.root_group();
    assert_eq!(
        root.link_names().unwrap(),
        vec!["ext".to_string(), "local".to_string()]
    );
    match root.link_class("ext").unwrap() {
        LinkClass::External { file, path } => {
            assert_eq!(file, target.to_string_lossy());
            assert_eq!(path, "/data");
        }
        other => panic!("expected an external link, got {other:?}"),
    }
    let ds = file.dataset("ext").unwrap();
    assert_eq!(ds.shape(), vec![4]);
    assert_eq!(ds.read_raw::<i32>().unwrap(), vec![0, 1, 2, 3]);

    std::fs::remove_file(&path).ok();
    std::fs::remove_file(&target).ok();
}

/// A contiguous dataset written under `libver=("v110","v110")` carries a
/// *version 4* data-layout message whose body is byte-identical to the
/// version-3 one. Rejecting the version dropped the dataset from the catalog
/// while a chunked dataset in the same file listed fine — the bisected pair
/// this test pins from both sides.
#[test]
fn contiguous_and_chunked_v110_both_list_and_read() {
    let Some(py) = python() else { return };
    let path = tmp("layout_v110");
    h5py_write(
        py,
        &path,
        "with h5py.File(PATH, 'w', libver=('v110', 'v110')) as f:\n\
         \x20   f.create_dataset('contig', data=np.arange(16, dtype='<i4'))\n\
         \x20   ds = f.create_dataset('chunky', (16,), chunks=(16,), dtype='<i4')\n\
         \x20   ds[...] = np.arange(16, dtype='<i4')\n\
         \x20   f.create_group('g')\n",
    );

    let file = H5File::open(&path).unwrap();
    let mut names = file.root_group().dataset_names().unwrap();
    names.sort();
    assert_eq!(names, vec!["chunky".to_string(), "contig".to_string()]);

    let expected: Vec<i32> = (0..16).collect();
    for name in ["contig", "chunky"] {
        let ds = file.dataset(name).unwrap();
        assert_eq!(ds.shape(), &[16], "{name}");
        assert_eq!(ds.read_raw::<i32>().unwrap(), expected, "{name}");
    }

    std::fs::remove_file(&path).ok();
}

/// The same dataset at every `libver` bound h5py offers. `latest` and
/// `v110` are the two that emit a version-4 contiguous layout; `earliest`
/// and `v108` emit version 3. All four must list the dataset and the group.
#[test]
fn contiguous_lists_at_every_libver_bound() {
    let Some(py) = python() else { return };
    for bound in ["earliest", "v108", "v110", "latest"] {
        let path = tmp(&format!("libver_{bound}"));
        let bounds = if bound == "latest" || bound == "earliest" {
            format!("'{bound}'")
        } else {
            format!("('{bound}', '{bound}')")
        };
        h5py_write(
            py,
            &path,
            &format!(
                "with h5py.File(PATH, 'w', libver={bounds}) as f:\n\
                 \x20   f.create_dataset('data', data=np.arange(16, dtype='<i4'))\n\
                 \x20   f.create_group('g')\n"
            ),
        );

        let file = H5File::open(&path).unwrap();
        let root = file.root_group();
        assert_eq!(
            root.dataset_names().unwrap(),
            vec!["data".to_string()],
            "libver {bound}"
        );
        assert_eq!(
            root.group_names().unwrap(),
            vec!["g".to_string()],
            "libver {bound}"
        );
        let data = file.dataset("data").unwrap().read_raw::<i32>().unwrap();
        assert_eq!(data, (0..16).collect::<Vec<i32>>(), "libver {bound}");

        std::fs::remove_file(&path).ok();
    }
}

/// Rewrite the one opaque (`V4`) datatype message in `path` as class 2,
/// `H5T_TIME` — a real HDF5 class this crate does not model, and the only way
/// to get one into a fixture, since h5py cannot create one. h5py's default
/// libver writes version-1 object headers, which carry no checksum, so the
/// message is editable in place.
fn retype_opaque_as_time(path: &std::path::Path, expected: usize) {
    let mut raw = std::fs::read(path).unwrap();
    // Version 1, class 5 (opaque), no tag, 4 bytes wide.
    const OPAQUE_V4: [u8; 8] = [0x15, 0, 0, 0, 4, 0, 0, 0];
    let hits: Vec<usize> = (0..raw.len() - 8)
        .filter(|&i| raw[i..i + 8] == OPAQUE_V4)
        .collect();
    assert_eq!(
        hits.len(),
        expected,
        "fixture must hold exactly {expected} opaque V4 datatype message(s)"
    );
    for at in hits {
        raw[at] = 0x12; // version 1, class 2 (H5T_TIME)
    }
    std::fs::write(path, &raw).unwrap();
}

/// One dataset per message this crate cannot decode: a datatype whose class it
/// does not model, and a virtual data layout. Each is a dataset the file
/// plainly contains, so each must be listed by name and must say what stands
/// in the way — the catalog walk used to drop them on the floor and report an
/// empty file. Opaque, object-reference and committed-datatype datasets were
/// cases here until each became readable.
#[test]
fn a_dataset_whose_message_does_not_decode_is_listed_and_says_why() {
    let Some(py) = python() else { return };
    // (name, h5py statements, the word the reason must name, opaque messages
    // to retype as H5T_TIME afterwards)
    let cases: [(&str, &str, &str, usize); 2] = [
        (
            "time",
            "f.create_dataset('x', data=np.arange(4, dtype='u1').view('V4'))",
            "datatype",
            1,
        ),
        (
            "virtual",
            "src = np.arange(4, dtype='<i4')\n\
             \x20   f.create_dataset('src', data=src)\n\
             \x20   layout = h5py.VirtualLayout(shape=(4,), dtype='<i4')\n\
             \x20   layout[...] = h5py.VirtualSource(f['src'])\n\
             \x20   f.create_virtual_dataset('x', layout)",
            "data layout",
            0,
        ),
    ];

    for (case, body, blame, opaque_messages) in cases {
        let path = tmp(&format!("undecodable_{case}"));
        h5py_write(
            py,
            &path,
            &format!(
                "with h5py.File(PATH, 'w') as f:\n\
                 \x20   {body}\n\
                 \x20   f.create_dataset('ok', data=np.arange(4, dtype='<i4'))\n"
            ),
        );
        if opaque_messages > 0 {
            retype_opaque_as_time(&path, opaque_messages);
        }

        let file = H5File::open(&path).unwrap();
        let root = file.root_group();
        let names = root.dataset_names().unwrap();
        assert!(names.contains(&"x".to_string()), "{case}: listed {names:?}");
        assert!(
            names.contains(&"ok".to_string()),
            "{case}: listed {names:?}"
        );

        let why = root
            .unreadable_reason("x")
            .unwrap()
            .unwrap_or_else(|| panic!("{case}: 'x' reports no reason"));
        assert!(why.contains(blame), "{case}: {why}");
        assert_eq!(root.unreadable_reason("ok").unwrap(), None, "{case}");

        match file.dataset("x").err() {
            Some(Hdf5Error::Unsupported(msg)) => assert!(msg.contains(blame), "{case}: {msg}"),
            other => panic!("{case}: expected an unsupported-feature error, got {other:?}"),
        }
        // The unreadable object must not cost the readable one.
        assert_eq!(
            file.dataset("ok").unwrap().read_raw::<i32>().unwrap(),
            (0..4).collect::<Vec<i32>>(),
            "{case}"
        );

        std::fs::remove_file(&path).ok();
    }
}

/// Reopening a file for writing rewrites every group object header from the
/// writer's registry, and the registry modelled hard links only — so a soft
/// or external link the file already held was erased by a rewrite that had
/// nothing to do with it. h5py writes the links, rust appends something
/// unrelated and closes, h5py checks that every link came back with its kind
/// and value intact.
#[test]
fn reopening_for_write_preserves_soft_and_external_links() {
    let Some(py) = python() else { return };
    let target = tmp("preserve_extlink_target");
    let path = tmp("preserve_links");
    h5py_write(
        py,
        &target,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f.create_dataset('data', data=np.arange(4, dtype='<i4'))\n",
    );
    // libver='latest' because the reopen path refuses a v0/v1-superblock file.
    h5py_write(
        py,
        &path,
        &format!(
            "with h5py.File(PATH, 'w', libver='latest') as f:\n\
             \x20   f.create_dataset('kept', data=np.arange(4, dtype='<i4'))\n\
             \x20   g = f.create_group('g')\n\
             \x20   g.create_dataset('inner', data=np.arange(4, dtype='<i4'))\n\
             \x20   f['soft'] = h5py.SoftLink('/kept')\n\
             \x20   f['dangling'] = h5py.SoftLink('/nowhere')\n\
             \x20   g['nested_soft'] = h5py.SoftLink('/g/inner')\n\
             \x20   f['ext'] = h5py.ExternalLink(r'{}', '/data')\n",
            target.display()
        ),
    );

    {
        let file = H5File::open_rw(&path).unwrap();
        // The links the writer is carrying are listed, with their own kinds.
        let root = file.root_group();
        assert!(matches!(
            root.link_class("soft").unwrap(),
            LinkClass::Soft { path } if path == "/kept"
        ));
        assert!(matches!(
            root.link_class("ext").unwrap(),
            LinkClass::External { path, .. } if path == "/data"
        ));
        assert!(root.link_names().unwrap().contains(&"dangling".to_string()));

        // Something unrelated, so every group header gets rewritten.
        file.new_dataset::<i32>()
            .shape([4usize])
            .create("added")
            .unwrap()
            .write_raw(&[9i32, 9, 9, 9])
            .unwrap();
        file.close().unwrap();
    }

    h5py_write(
        py,
        &path,
        &format!(
            "with h5py.File(PATH, 'r') as f:\n\
             \x20   soft = f.get('soft', getlink=True)\n\
             \x20   assert isinstance(soft, h5py.SoftLink), soft\n\
             \x20   assert soft.path == '/kept', soft.path\n\
             \x20   dang = f.get('dangling', getlink=True)\n\
             \x20   assert isinstance(dang, h5py.SoftLink), dang\n\
             \x20   assert dang.path == '/nowhere', dang.path\n\
             \x20   nested = f['g'].get('nested_soft', getlink=True)\n\
             \x20   assert isinstance(nested, h5py.SoftLink), nested\n\
             \x20   assert nested.path == '/g/inner', nested.path\n\
             \x20   ext = f.get('ext', getlink=True)\n\
             \x20   assert isinstance(ext, h5py.ExternalLink), ext\n\
             \x20   assert ext.filename == r'{}', ext.filename\n\
             \x20   assert ext.path == '/data', ext.path\n\
             \x20   assert f['soft'][...].tolist() == [0, 1, 2, 3]\n\
             \x20   assert f['ext'][...].tolist() == [0, 1, 2, 3]\n\
             \x20   assert f['added'][...].tolist() == [9, 9, 9, 9]\n\
             \x20   assert f['kept'][...].tolist() == [0, 1, 2, 3]\n\
             \x20   assert f['g/inner'][...].tolist() == [0, 1, 2, 3]\n",
            target.display()
        ),
    );

    std::fs::remove_file(&path).ok();
    std::fs::remove_file(&target).ok();
}

/// A group whose only child is a link the writer cannot express: nothing
/// else would put it in the registry, so a rewrite would drop the group and
/// the link with it.
#[test]
fn reopening_for_write_keeps_a_group_holding_only_a_soft_link() {
    let Some(py) = python() else { return };
    let path = tmp("preserve_lone_softlink");
    h5py_write(
        py,
        &path,
        "with h5py.File(PATH, 'w', libver='latest') as f:\n\
         \x20   f.create_dataset('data', data=np.arange(4, dtype='<i4'))\n\
         \x20   f.create_group('only').__setitem__('s', h5py.SoftLink('/data'))\n",
    );

    {
        let file = H5File::open_rw(&path).unwrap();
        file.new_dataset::<i32>()
            .shape([2usize])
            .create("added")
            .unwrap()
            .write_raw(&[1i32, 2])
            .unwrap();
        file.close().unwrap();
    }

    h5py_write(
        py,
        &path,
        "with h5py.File(PATH, 'r') as f:\n\
         \x20   assert 'only' in f, list(f.keys())\n\
         \x20   s = f['only'].get('s', getlink=True)\n\
         \x20   assert isinstance(s, h5py.SoftLink), s\n\
         \x20   assert s.path == '/data', s.path\n\
         \x20   assert f['only/s'][...].tolist() == [0, 1, 2, 3]\n",
    );

    std::fs::remove_file(&path).ok();
}

/// A name a preserved link already holds is taken: creating over it would
/// emit two `Link` messages of one name into a group, which is an invalid
/// file rather than a replacement.
#[test]
fn creating_over_a_preserved_link_name_is_refused() {
    let Some(py) = python() else { return };
    let path = tmp("preserve_name_clash");
    h5py_write(
        py,
        &path,
        "with h5py.File(PATH, 'w', libver='latest') as f:\n\
         \x20   f.create_dataset('data', data=np.arange(4, dtype='<i4'))\n\
         \x20   f['soft'] = h5py.SoftLink('/data')\n",
    );

    let file = H5File::open_rw(&path).unwrap();
    let err = file
        .new_dataset::<i32>()
        .shape([2usize])
        .create("soft")
        .err()
        .expect("creating over an existing link name must be refused");
    assert!(format!("{err}").contains("already exists"), "{err}");
    file.close().unwrap();

    std::fs::remove_file(&path).ok();
}

/// An external link naming a bare file name resolves against the directory
/// holding the file that names it — not the working directory — and the
/// remainder of the path is traversed inside the target, including through a
/// second external link.
#[test]
fn external_link_resolves_against_the_parent_directory_and_nests() {
    let Some(py) = python() else { return };
    let dir = tmp_dir("extlink_relative");
    let (first, second, third) = (
        dir.join("first.h5"),
        dir.join("second.h5"),
        dir.join("third.h5"),
    );

    h5py_write(
        py,
        &third,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f.create_dataset('end', data=np.arange(6, dtype='<f8'))\n",
    );
    // `libver='latest'` keeps this case about link following: at the default
    // bound `deep` lands in symbol-table storage under a link-storage root,
    // which is its own case (`a_group_keeps_its_children_when_its_storage_
    // differs_from_its_parents`).
    h5py_write(
        py,
        &second,
        "with h5py.File(PATH, 'w', libver='latest') as f:\n\
         \x20   f.create_group('deep').create_dataset('payload', data=np.arange(4, dtype='<i4'))\n\
         \x20   f['onward'] = h5py.ExternalLink('third.h5', '/end')\n",
    );
    // Bare file names: only the parent directory rule can resolve them, since
    // the test process runs from the crate root.
    h5py_write(
        py,
        &first,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['group'] = h5py.ExternalLink('second.h5', '/deep')\n\
         \x20   f['chain'] = h5py.ExternalLink('second.h5', '/onward')\n",
    );

    let file = H5File::open(&first).unwrap();
    // One hop, then a path continuing inside the target's group.
    let ds = file.dataset("group/payload").unwrap();
    assert_eq!(ds.read_raw::<i32>().unwrap(), vec![0, 1, 2, 3]);
    // Two hops: first.h5 -> second.h5 -> third.h5.
    let chained = file.dataset("chain").unwrap();
    assert_eq!(chained.shape(), vec![6]);
    assert_eq!(
        chained.read_raw::<f64>().unwrap(),
        vec![0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
    );
    drop(file);

    std::fs::remove_dir_all(&dir).ok();
}

/// `HDF5_EXT_PREFIX` is searched before the parent file's own directory, so a
/// target that moved out from beside its master is found again by setting it —
/// and the failure without it names every path that was tried.
#[test]
fn external_link_target_is_found_through_hdf5_ext_prefix() {
    let Some(py) = python() else { return };
    let home = tmp_dir("extprefix_home");
    let away = tmp_dir("extprefix_away");
    let master = home.join("master.h5");
    let target = away.join("moved.h5");

    h5py_write(
        py,
        &target,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f.create_dataset('v', data=np.arange(3, dtype='<i4'))\n",
    );
    h5py_write(
        py,
        &master,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['moved'] = h5py.ExternalLink('moved.h5', '/v')\n",
    );

    std::env::remove_var("HDF5_EXT_PREFIX");
    let file = H5File::open(&master).unwrap();
    match file.dataset("moved").err() {
        Some(Hdf5Error::ExternalFileNotFound {
            link,
            file,
            searched,
        }) => {
            assert_eq!(link, "moved");
            assert_eq!(file, "moved.h5");
            // The parent directory and the working directory were both tried.
            assert!(
                searched.iter().any(|p| p.contains("extprefix_home")),
                "{searched:?}"
            );
            assert!(searched.iter().any(|p| p == "moved.h5"), "{searched:?}");
        }
        other => panic!("expected the target file to be reported missing, got {other:?}"),
    }
    drop(file);

    // A two-component prefix list: the first misses, the second resolves.
    std::env::set_var(
        "HDF5_EXT_PREFIX",
        format!("{}:{}", home.display(), away.display()),
    );
    let file = H5File::open(&master).unwrap();
    assert_eq!(
        file.dataset("moved").unwrap().read_raw::<i32>().unwrap(),
        vec![0, 1, 2]
    );
    drop(file);
    std::env::remove_var("HDF5_EXT_PREFIX");

    std::fs::remove_dir_all(&home).ok();
    std::fs::remove_dir_all(&away).ok();
}

/// A dangling external link is listed like any other, and says which half is
/// missing: the file it names, or the object inside it.
#[test]
fn a_dangling_external_link_reports_the_file_or_the_object() {
    let Some(py) = python() else { return };
    let dir = tmp_dir("extlink_dangling");
    let master = dir.join("master.h5");
    let target = dir.join("target.h5");

    h5py_write(
        py,
        &target,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f.create_dataset('there', data=np.arange(2, dtype='<i4'))\n",
    );
    h5py_write(
        py,
        &master,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['no_file'] = h5py.ExternalLink('absent.h5', '/there')\n\
         \x20   f['no_object'] = h5py.ExternalLink('target.h5', '/missing')\n",
    );

    std::env::remove_var("HDF5_EXT_PREFIX");
    let file = H5File::open(&master).unwrap();
    let root = file.root_group();
    // Both dangle; both are still names the file holds.
    assert_eq!(
        root.link_names().unwrap(),
        vec!["no_file".to_string(), "no_object".to_string()]
    );
    match file.dataset("no_file").err() {
        Some(Hdf5Error::ExternalFileNotFound { file, .. }) => assert_eq!(file, "absent.h5"),
        other => panic!("expected a missing target file, got {other:?}"),
    }
    match file.dataset("no_object").err() {
        Some(Hdf5Error::DanglingLink { link, target }) => {
            assert_eq!(link, "no_object");
            assert_eq!(target, "target.h5::/missing");
        }
        other => panic!("expected a dangling link, got {other:?}"),
    }
    drop(file);

    std::fs::remove_dir_all(&dir).ok();
}

/// Two links naming one file share one open handle for the life of the
/// parent `H5File`. Unlinking the target after the first read is what makes
/// that observable: a second open would find nothing, a cached handle still
/// reads.
#[cfg(unix)]
#[test]
fn links_to_one_external_file_share_one_open_handle() {
    let Some(py) = python() else { return };
    let dir = tmp_dir("extlink_cache");
    let master = dir.join("master.h5");
    let target = dir.join("target.h5");

    h5py_write(
        py,
        &target,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f.create_dataset('a', data=np.arange(2, dtype='<i4'))\n\
         \x20   f.create_dataset('b', data=np.arange(3, dtype='<i4'))\n",
    );
    h5py_write(
        py,
        &master,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['first'] = h5py.ExternalLink('target.h5', '/a')\n\
         \x20   f['second'] = h5py.ExternalLink('target.h5', '/b')\n",
    );

    std::env::remove_var("HDF5_EXT_PREFIX");
    let file = H5File::open(&master).unwrap();
    assert_eq!(
        file.dataset("first").unwrap().read_raw::<i32>().unwrap(),
        vec![0, 1]
    );
    std::fs::remove_file(&target).unwrap();
    assert_eq!(
        file.dataset("second").unwrap().read_raw::<i32>().unwrap(),
        vec![0, 1, 2]
    );
    drop(file);

    std::fs::remove_dir_all(&dir).ok();
}

/// Two files that link to each other are a cycle. Resolution stops at the
/// same link bound libhdf5 uses and says so, rather than recursing until the
/// stack or the file-descriptor table runs out.
#[test]
fn an_external_link_cycle_stops_at_the_link_bound() {
    let Some(py) = python() else { return };
    let dir = tmp_dir("extlink_cycle");
    let (a, b) = (dir.join("a.h5"), dir.join("b.h5"));

    h5py_write(
        py,
        &a,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['loop'] = h5py.ExternalLink('b.h5', '/loop')\n",
    );
    h5py_write(
        py,
        &b,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['loop'] = h5py.ExternalLink('a.h5', '/loop')\n",
    );

    std::env::remove_var("HDF5_EXT_PREFIX");
    let file = H5File::open(&a).unwrap();
    let err = file
        .dataset("loop")
        .err()
        .expect("a link cycle must not resolve");
    let text = format!("{err}");
    assert!(text.contains("external links"), "{text}");
    assert!(text.contains("cycle"), "{text}");
    drop(file);

    std::fs::remove_dir_all(&dir).ok();
}

/// Write mode carries external links through a rewrite but never follows one:
/// every write-side path that crosses one is refused by name, and the link
/// itself survives the session intact.
#[test]
fn write_mode_refuses_every_path_through_an_external_link() {
    let Some(py) = python() else { return };
    let dir = tmp_dir("extlink_write");
    let master = dir.join("master.h5");
    let target = dir.join("target.h5");

    h5py_write(
        py,
        &target,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f.create_group('g').create_dataset('d', data=np.arange(2, dtype='<i4'))\n",
    );
    h5py_write(
        py,
        &master,
        "with h5py.File(PATH, 'w', libver='latest') as f:\n\
         \x20   f.create_dataset('local', data=np.arange(2, dtype='<i4'))\n\
         \x20   f['ext'] = h5py.ExternalLink('target.h5', '/g')\n",
    );

    let refused = |err: Option<Hdf5Error>, what: &str| match err {
        Some(Hdf5Error::Unsupported(why)) => {
            assert!(why.contains("external link 'ext'"), "{what}: {why}");
        }
        other => panic!("{what} must be refused by name, got {other:?}"),
    };

    {
        let file = H5File::open_rw(&master).unwrap();
        refused(file.dataset_writer("ext").err(), "reopening the link");
        refused(
            file.new_dataset::<i32>()
                .shape([2usize])
                .create("ext/new")
                .err(),
            "creating through the link",
        );
        refused(file.delete_dataset("ext").err(), "deleting the link");
        refused(
            file.delete_group("ext/g").err(),
            "deleting through the link",
        );
        refused(
            file.create_group("ext/sub").err(),
            "creating a group through the link",
        );
        // Something unrelated still writes, and the link rides through it.
        file.new_dataset::<i32>()
            .shape([2usize])
            .create("added")
            .unwrap()
            .write_raw(&[7i32, 8])
            .unwrap();
        file.close().unwrap();
    }

    std::env::remove_var("HDF5_EXT_PREFIX");
    let file = H5File::open(&master).unwrap();
    match file.root_group().link_class("ext").unwrap() {
        LinkClass::External { file, path } => {
            assert_eq!(file, "target.h5");
            assert_eq!(path, "/g");
        }
        other => panic!("the external link must survive the rewrite, got {other:?}"),
    }
    // And the reader still follows it after the writer touched the file.
    assert_eq!(
        file.dataset("ext/d").unwrap().read_raw::<i32>().unwrap(),
        vec![0, 1]
    );
    drop(file);

    std::fs::remove_dir_all(&dir).ok();
}

/// A group handle belongs to one file, so a group path that crosses an
/// external link is refused with the target named — the alternative is a
/// handle whose every listing comes back empty.
#[test]
fn a_group_path_across_an_external_link_is_named_not_empty() {
    let Some(py) = python() else { return };
    let dir = tmp_dir("extlink_group");
    let master = dir.join("master.h5");
    let target = dir.join("target.h5");

    h5py_write(
        py,
        &target,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f.create_group('g').create_dataset('d', data=np.arange(2, dtype='<i4'))\n",
    );
    h5py_write(
        py,
        &master,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['ext'] = h5py.ExternalLink('target.h5', '/g')\n",
    );

    std::env::remove_var("HDF5_EXT_PREFIX");
    let file = H5File::open(&master).unwrap();
    match file.root_group().group("ext").err() {
        Some(Hdf5Error::Unsupported(why)) => {
            assert!(why.contains("target.h5"), "{why}");
            assert!(why.contains("does not cross into another file"), "{why}");
        }
        other => panic!("expected a named refusal, got {other:?}"),
    }
    // The dataset under it still opens: the link is followed, the handle is not.
    assert_eq!(
        file.dataset("ext/d").unwrap().read_raw::<i32>().unwrap(),
        vec![0, 1]
    );
    drop(file);

    std::fs::remove_dir_all(&dir).ok();
}

/// Which storage a group uses — `Link` messages or the legacy symbol table —
/// is a property of that group, not of the file. One link the old format
/// cannot express (an external link) or one creation-order-tracked group
/// migrates just that group, so a mixed file is what h5py writes by default,
/// not a curiosity. Walking a group the way its *parent* is stored finds no
/// children at all, which listed the group and dropped its whole subtree.
/// Both directions of the mismatch are here.
#[test]
fn a_group_keeps_its_children_when_its_storage_differs_from_its_parents() {
    let Some(py) = python() else { return };

    // Symbol-table child under a link-storage root: `track_order` on the file
    // migrates the root, `legacy` is created without it and stays behind.
    let modern_root = tmp("mixed_modern_root");
    h5py_write(
        py,
        &modern_root,
        "with h5py.File(PATH, 'w', track_order=True) as f:\n\
         \x20   g = f.create_group('legacy')\n\
         \x20   g.create_dataset('a', data=np.arange(3, dtype='<i4'))\n\
         \x20   g.create_group('inner').create_dataset('c', data=np.arange(5, dtype='<i4'))\n",
    );

    let file = H5File::open(&modern_root).unwrap();
    assert_eq!(
        file.dataset_names(),
        vec!["legacy/a".to_string(), "legacy/inner/c".to_string()]
    );
    let legacy = file.root_group().group("legacy").unwrap();
    assert_eq!(
        legacy.link_names().unwrap(),
        vec!["a".to_string(), "inner".to_string()]
    );
    assert_eq!(
        file.dataset("legacy/inner/c")
            .unwrap()
            .read_raw::<i32>()
            .unwrap(),
        vec![0, 1, 2, 3, 4]
    );
    drop(file);
    std::fs::remove_file(&modern_root).ok();

    // Link-storage child under a symbol-table root: the root keeps the default
    // format, `modern` asks for creation-order tracking and migrates.
    let legacy_root = tmp("mixed_legacy_root");
    h5py_write(
        py,
        &legacy_root,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f.create_group('legacy').create_dataset('a', data=np.arange(3, dtype='<i4'))\n\
         \x20   n = f.create_group('modern', track_order=True)\n\
         \x20   n.create_dataset('b', data=np.arange(4, dtype='<i4'))\n\
         \x20   n.create_group('inner').create_dataset('c', data=np.arange(5, dtype='<i4'))\n",
    );

    let file = H5File::open(&legacy_root).unwrap();
    assert_eq!(
        file.dataset_names(),
        vec![
            "legacy/a".to_string(),
            "modern/b".to_string(),
            "modern/inner/c".to_string()
        ]
    );
    let modern = file.root_group().group("modern").unwrap();
    assert_eq!(
        modern.link_names().unwrap(),
        vec!["b".to_string(), "inner".to_string()]
    );
    assert_eq!(
        file.dataset("modern/inner/c")
            .unwrap()
            .read_raw::<i32>()
            .unwrap(),
        vec![0, 1, 2, 3, 4]
    );
    drop(file);
    std::fs::remove_file(&legacy_root).ok();
}

/// A dataset built on a committed (named) datatype does not store a type of
/// its own — it stores a *reference* to the object header holding it. Reading
/// those bytes as a datatype does not fail loudly: the first byte of the
/// reference is its version, which the datatype decoder reads as a version
/// and a class of its own, so the dataset came back as one this crate cannot
/// read.
#[test]
fn a_dataset_that_shares_a_committed_datatype_reads_through_the_reference() {
    let Some(py) = python() else { return };
    let path = tmp("shared_datatype");
    h5py_write(
        py,
        &path,
        "from h5py import h5d, h5s\n\
         with h5py.File(PATH, 'w') as f:\n\
         \x20   f['t'] = np.dtype('<i4')\n\
         \x20   own = f.create_dataset('own', data=np.arange(8, dtype='<i4'))\n\
         \x20   sid = h5s.create_simple((8,))\n\
         \x20   dsid = h5d.create(f.id, b'shared', f['t'].id, sid)\n\
         \x20   dsid.write(h5s.ALL, h5s.ALL, np.arange(8, dtype='<i4'))\n",
    );

    let file = H5File::open(&path).unwrap();
    let expected: Vec<i32> = (0..8).collect();
    assert_eq!(
        file.root_group().unreadable_reason("shared").unwrap(),
        None,
        "a shared datatype must not make the dataset unreadable"
    );
    let shared = file.dataset("shared").unwrap();
    assert_eq!(shared.shape(), vec![8]);
    assert_eq!(shared.read_raw::<i32>().unwrap(), expected);
    // The type the reference resolves to is the committed one, decoded the
    // same as a dataset carrying its own copy.
    assert_eq!(
        format!("{:?}", shared.datatype().unwrap()),
        format!("{:?}", file.dataset("own").unwrap().datatype().unwrap())
    );

    std::fs::remove_file(&path).ok();
}

/// A committed (named) datatype is an object, not a property of the datasets
/// that use it: `H5Tcommit` gives it an object header and a name, and h5py
/// hands it back as a `Datatype`. Classifying it as neither a group nor a
/// dataset left its name in the file with nothing behind it — the link was
/// listed, and every accessor answered as if the object were not there.
#[test]
fn a_committed_datatype_is_listed_and_opens_as_an_object_of_its_own() {
    let Some(py) = python() else { return };
    let path = tmp("named_datatype");
    h5py_write(
        py,
        &path,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['t'] = np.dtype('<i4')\n\
         \x20   f.create_dataset('own', data=np.arange(4, dtype='<i4'))\n\
         \x20   f.create_group('g')\n",
    );

    let file = H5File::open(&path).unwrap();
    assert_eq!(file.named_datatype_names(), vec!["t".to_string()]);
    let root = file.root_group();
    assert_eq!(root.named_datatype_names().unwrap(), vec!["t".to_string()]);
    // It belongs to no other listing, and the link to it is still a link.
    assert_eq!(root.dataset_names().unwrap(), vec!["own".to_string()]);
    assert_eq!(root.group_names().unwrap(), vec!["g".to_string()]);
    assert_eq!(
        root.link_names().unwrap(),
        vec!["g".to_string(), "own".to_string(), "t".to_string()]
    );
    assert!(matches!(root.link_class("t").unwrap(), LinkClass::Hard));

    // The committed type decodes to what a dataset carrying its own copy of
    // the same type decodes to.
    let t = file.named_datatype("t").unwrap();
    assert_eq!(t.name(), "t");
    assert_eq!(
        format!("{:?}", t.datatype().unwrap()),
        format!("{:?}", file.dataset("own").unwrap().datatype().unwrap())
    );
    assert_eq!(root.named_datatype("t").unwrap().name(), "t");

    // A name that is not one is an absence, not an empty answer.
    assert!(matches!(
        file.named_datatype("own"),
        Err(Hdf5Error::NotFound(_))
    ));
    assert!(matches!(
        file.named_datatype("nope"),
        Err(Hdf5Error::NotFound(_))
    ));

    std::fs::remove_file(&path).ok();
}

/// A committed datatype can sit in any group and can carry attributes of its
/// own — `H5Aopen` works on it exactly as on a dataset.
#[test]
fn a_committed_datatype_in_a_group_carries_its_own_attributes() {
    let Some(py) = python() else { return };
    let path = tmp("named_datatype_attrs");
    h5py_write(
        py,
        &path,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   g = f.create_group('g')\n\
         \x20   g['t'] = np.dtype('<f8')\n\
         \x20   g['t'].attrs['units'] = 'mm'\n\
         \x20   g['t'].attrs['scale'] = np.int32(7)\n",
    );

    let file = H5File::open(&path).unwrap();
    assert_eq!(file.named_datatype_names(), vec!["g/t".to_string()]);
    let g = file.root_group().group("g").unwrap();
    assert_eq!(g.named_datatype_names().unwrap(), vec!["t".to_string()]);
    // The root group holds none of its own.
    assert!(file.root_group().named_datatype_names().unwrap().is_empty());

    for t in [
        file.named_datatype("g/t").unwrap(),
        g.named_datatype("t").unwrap(),
    ] {
        assert_eq!(t.datatype().unwrap().element_size(), 8);
        // Sorted: this crate lists attributes in object-header order, not the
        // name order h5py indexes by, for every object alike.
        let mut names = t.attr_names().unwrap();
        names.sort();
        assert_eq!(names, vec!["scale".to_string(), "units".to_string()]);
        assert_eq!(t.attr("units").unwrap().read_string().unwrap(), "mm");
        assert_eq!(t.attr("scale").unwrap().read_numeric::<i32>().unwrap(), 7);
    }

    std::fs::remove_file(&path).ok();
}

/// A committed datatype whose type this crate cannot decode is still an
/// object with a name: it stays in the listing and it still opens, and the
/// reason lands on the type rather than turning the object into an absence.
#[test]
fn a_committed_datatype_this_crate_cannot_decode_is_still_listed() {
    let Some(py) = python() else { return };
    let path = tmp("named_datatype_opaque");
    h5py_write(
        py,
        &path,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['t'] = np.dtype('V4')\n\
         \x20   f['t'].attrs['tag'] = np.int32(3)\n",
    );
    retype_opaque_as_time(&path, 1);

    let file = H5File::open(&path).unwrap();
    assert_eq!(file.named_datatype_names(), vec!["t".to_string()]);
    let t = file.named_datatype("t").unwrap();
    let why = match t.datatype() {
        Err(Hdf5Error::Unsupported(why)) => why,
        other => panic!("expected an unsupported type, got {other:?}"),
    };
    assert!(
        why.contains("datatype"),
        "the reason must name the datatype: {why}"
    );
    // Its attributes are readable regardless: they do not depend on the type.
    assert_eq!(t.attr("tag").unwrap().read_numeric::<i32>().unwrap(), 3);

    std::fs::remove_file(&path).ok();
}

/// An external link reaching a committed datatype resolves through the same
/// traversal every other object uses, and the type comes back decoded from
/// the file that holds it.
#[test]
fn a_committed_datatype_reached_through_an_external_link_resolves() {
    let Some(py) = python() else { return };
    let dir = tmp_dir("named_datatype_extlink");
    let (master, target) = (dir.join("master.h5"), dir.join("target.h5"));

    h5py_write(
        py,
        &target,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['t'] = np.dtype('<u2')\n\
         \x20   f['t'].attrs['tag'] = np.int32(11)\n",
    );
    h5py_write(
        py,
        &master,
        "with h5py.File(PATH, 'w') as f:\n\
         \x20   f['far'] = h5py.ExternalLink('target.h5', '/t')\n",
    );

    let file = H5File::open(&master).unwrap();
    // The link is the master's; the object is not, so it is not in the
    // master's own listing.
    assert!(file.named_datatype_names().is_empty());
    let t = file.named_datatype("far").unwrap();
    assert_eq!(t.datatype().unwrap().element_size(), 2);
    assert_eq!(t.attr("tag").unwrap().read_numeric::<i32>().unwrap(), 11);
    drop(file);

    std::fs::remove_dir_all(&dir).ok();
}
