//! Shared object header messages (SOHM), read side.
//!
//! A message whose `H5O_MSG_FLAG_SHARED` bit is set does not hold the message:
//! it holds a pointer to the fractal heap the shared-message table names, or to
//! the object header of a committed datatype. Decoding that pointer as if it
//! were the message is a silent misparse — the reader sees a datatype of the
//! wrong class and an attribute that is not there.
//!
//! Fixtures come from `tests/fixtures/gen_sohm.sh`; h5py has no binding for
//! `H5Pset_shared_mesg_index`, so they are generated by a C program and checked
//! in. Each shares datatype, dataspace and attribute messages through one
//! index; `sohm_list.h5` leaves that index in its list form, `sohm_btree.h5`
//! forces the phase change to a version-2 B-tree, `sohm_paged.h5` adds a file
//! space info message to the same superblock extension, and
//! `sohm_named_attr.h5` shares the attribute onto the committed datatype too.

use std::path::PathBuf;

use rust_hdf5::{DatatypeMessage, H5File};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// The four `sharedN` datasets differ only in their data; every one of them
/// after the first stores its datatype, dataspace and attribute as heap
/// pointers.
fn check_shared_datasets(name: &str) {
    let file = H5File::open(fixture(name)).unwrap();

    let mut names = file.dataset_names();
    names.sort();
    assert_eq!(
        names,
        vec!["shared0", "shared1", "shared2", "shared3", "uses_named"],
        "{name}"
    );

    for i in 0..4 {
        let ds = file.dataset(&format!("shared{i}")).unwrap();
        assert_eq!(ds.shape(), vec![8], "shared{i} of {name}");
        match ds.datatype().unwrap() {
            DatatypeMessage::FixedPoint { size, signed, .. } => {
                assert_eq!((size, signed), (4, true), "shared{i} of {name}");
            }
            other => panic!("shared{i} of {name} decoded as {other:?}"),
        }
        let data: Vec<i32> = ds.read_raw().unwrap();
        let expected: Vec<i32> = (0..8).map(|j| i * 10 + j).collect();
        assert_eq!(data, expected, "shared{i} of {name}");
    }
}

/// The identical `cal` attribute on all four datasets: its datatype and
/// dataspace are shared inside the attribute message, flagged in the
/// attribute's own flags byte rather than the object-header message's.
fn check_shared_attribute(name: &str) {
    let file = H5File::open(fixture(name)).unwrap();
    for i in 0..4 {
        let ds = file.dataset(&format!("shared{i}")).unwrap();
        assert_eq!(ds.attr_names().unwrap(), vec!["cal"], "shared{i} of {name}");
        let values: Vec<f64> = ds.attr("cal").unwrap().read_numeric_as().unwrap();
        assert_eq!(values, vec![0.5, 1.5, 2.5], "shared{i} of {name}");
    }
}

/// `uses_named` was created with a committed datatype, so its datatype message
/// is a pointer to the `named_i32` object header rather than a heap ID.
fn check_committed_datatype(name: &str) {
    let file = H5File::open(fixture(name)).unwrap();
    let ds = file.dataset("uses_named").unwrap();
    assert_eq!(ds.shape(), vec![8], "{name}");
    match ds.datatype().unwrap() {
        DatatypeMessage::FixedPoint { size, signed, .. } => {
            assert_eq!((size, signed), (4, true), "{name}");
        }
        other => panic!("uses_named of {name} decoded as {other:?}"),
    }
    let data: Vec<i32> = ds.read_raw().unwrap();
    assert_eq!(data, (100..108).collect::<Vec<i32>>(), "{name}");
}

#[test]
fn shared_message_table_is_read_from_the_superblock_extension() {
    let file = H5File::open(fixture("sohm_list.h5")).unwrap();
    let smt = file
        .superblock_extension()
        .shared_message_table
        .expect("sohm_list.h5 declares a shared message table");
    assert_eq!(smt.version, 0);
    assert_eq!(smt.nindexes, 1);
    assert_ne!(smt.table_address, u64::MAX);
}

#[test]
fn shared_datatype_and_dataspace_resolve_through_a_list_index() {
    check_shared_datasets("sohm_list.h5");
}

#[test]
fn shared_datatype_and_dataspace_resolve_through_a_btree_index() {
    check_shared_datasets("sohm_btree.h5");
}

#[test]
fn shared_attribute_fields_resolve_through_a_list_index() {
    check_shared_attribute("sohm_list.h5");
}

#[test]
fn shared_attribute_fields_resolve_through_a_btree_index() {
    check_shared_attribute("sohm_btree.h5");
}

#[test]
fn committed_datatype_resolves_through_its_object_header() {
    check_committed_datatype("sohm_list.h5");
    check_committed_datatype("sohm_btree.h5");
}
