//! The superblock extension object header and the v1 B-tree "K" values.
//!
//! Fixtures are generated by `tests/fixtures/gen_sbext.sh` (h5py binds neither
//! `H5Pset_sym_k`/`H5Pset_istore_k` nor `H5Pset_file_space_strategy`):
//!
//!   `btreek_legacy.h5`  K values in a version-1 superblock, no extension.
//!   `sbext_btreek.h5`   the same K values in the extension's B-tree-K message.
//!   `sbext_paged.h5`    paged aggregation with persisted free-space managers.

use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};

use rust_hdf5::{FileSpaceStrategy, H5File};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// Per-test unique temp path; cargo runs tests in parallel.
fn unique_tmp(label: &str) -> PathBuf {
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    let dir = std::env::temp_dir().join(format!(
        "rust_hdf5_sbext_{}_{}_{}",
        label,
        std::process::id(),
        n
    ));
    std::fs::create_dir_all(&dir).unwrap();
    dir.join(format!("{label}.h5"))
}

fn cleanup(path: &PathBuf) {
    let _ = std::fs::remove_file(path);
    if let Some(dir) = path.parent() {
        let _ = std::fs::remove_dir_all(dir);
    }
}

/// `sym_leaf_k = 110` puts 209 entries — 8368 bytes — in the root group's
/// single symbol table node, and `istore_k = 64` puts all 100 chunk records in
/// one chunk B-tree node. Sizing either node by the library default (4 and 32)
/// reads it short, so every object in the file is reachable only when the
/// superblock's own K values are honoured.
#[test]
fn non_default_k_from_the_superblock_sizes_every_v1_node() {
    let file = H5File::open(fixture("btreek_legacy.h5")).unwrap();

    let mut names = file.dataset_names();
    names.sort();
    assert_eq!(
        names,
        vec!["chunked", "d0", "d1", "d2", "d3", "d4", "d5", "d6", "d7"]
    );

    // The 100-chunk B-tree node decodes in full.
    let chunked: Vec<i32> = file.dataset("chunked").unwrap().read_raw().unwrap();
    assert_eq!(chunked.len(), 1000);
    assert_eq!(chunked[0], 0);
    assert_eq!(chunked[999], 999);

    // A dataset whose symbol-table entry sits past the old fixed 8 KiB window.
    let d7: Vec<i32> = file.dataset("d7").unwrap().read_raw().unwrap();
    assert_eq!(d7, vec![700, 701, 702, 703]);

    // No extension: this file's K values live in the superblock.
    assert_eq!(file.superblock_extension().btree_k, None);
}

/// The same content written with persisted free-space managers, which moves
/// the superblock to version 2 and the K values into the extension's B-tree-K
/// message. The message's three fields are ordered chunk, snode, sym-leaf.
#[test]
fn btree_k_message_is_read_from_the_superblock_extension() {
    let file = H5File::open(fixture("sbext_btreek.h5")).unwrap();
    let k = file
        .superblock_extension()
        .btree_k
        .expect("btree k message");
    assert_eq!(k.chunk_internal_k, 64);
    assert_eq!(k.snode_internal_k, 100);
    assert_eq!(k.sym_leaf_k, 110);
}

/// Paged aggregation with persisting free-space managers: strategy, page size
/// and the twelve manager addresses all come out of the file-space info
/// message. A reader that ignored it would take the file for a default-layout
/// one.
#[test]
fn file_space_info_message_reports_paged_persisted_allocation() {
    let file = H5File::open(fixture("sbext_paged.h5")).unwrap();
    let fs = file
        .superblock_extension()
        .file_space_info
        .expect("file space info message");
    assert_eq!(fs.version, 1);
    assert_eq!(fs.strategy, FileSpaceStrategy::Page);
    assert!(fs.persist);
    assert_eq!(fs.page_size, 8192);
    assert_eq!(fs.fs_addr.len(), 12);
    // At least one page-type manager was persisted.
    assert!(fs.fs_addr.iter().any(|&a| a != u64::MAX));
}

/// Free-space managers persisted without paging: the same message, strategy
/// FSM_AGGR (the zero-valued `H5F_fspace_strategy_t`, which is easy to read as
/// "no strategy byte present").
#[test]
fn file_space_info_message_reports_fsm_aggr_allocation() {
    let file = H5File::open(fixture("sbext_btreek.h5")).unwrap();
    let fs = file
        .superblock_extension()
        .file_space_info
        .expect("file space info message");
    assert_eq!(fs.strategy, FileSpaceStrategy::FsmAggr);
    assert!(fs.persist);
    assert_eq!(fs.fs_addr.len(), 12);
}

/// A file this crate writes has no extension at all, and must report so rather
/// than inventing defaults.
#[test]
fn a_file_without_an_extension_reports_no_messages() {
    let path = unique_tmp("no_extension");
    {
        let file = H5File::create(&path).unwrap();
        file.new_dataset::<i32>()
            .shape([4])
            .create("plain")
            .unwrap()
            .write_raw(&[1i32, 2, 3, 4])
            .unwrap();
        file.close().unwrap();
    }
    let file = H5File::open(&path).unwrap();
    assert_eq!(file.superblock_extension(), Default::default());
    cleanup(&path);
}
